### ISSUE TITLE
Location of auto trigger stl's?

### ISSUE THREAD

**Issue by will-o-matic** [Flygonial/Protean-Modular-Takedown-Blaster#2]
Hey, I'm working on building the solenoid variant, but I don't see the auto grip files in the repo.  Any chance you can point me to them?  

On another note, if you're looking for help with the coding side, hit me up.  I love a good hardware project.

**Comment by ghost** [comment]
Long ago I found them in the beta files linked in the readme. Are they still there? I transitioned to AEBs and have not kept up with flywheel projects.

**Comment by will-o-matic** [comment]
Ha right in front of my eyes.  Thank you!!
